# EVE Profit Calculator 2.0 - Development Docker Compose
# Fast development environment with hot reloading

version: '3.8'

services:
  # Backend Development (Go with hot reload)
  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: eve-profit-backend-dev
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      - GO_ENV=development
      - SERVER_PORT=9000
      - SDE_DB_PATH=/app/data/sqlite-latest.sqlite
      - CACHE_TTL=60
      - ESI_BASE_URL=https://esi.evetech.net
      - ESI_RATE_LIMIT=150
      - HOT_RELOAD=true
    volumes:
      - ./backend:/app
      - backend_cache:/go/pkg/mod
    networks:
      - eve-dev-network
    command: go run cmd/server/main.go

  # Frontend Development (Vite with hot reload)
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: eve-profit-frontend-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:9000
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    networks:
      - eve-dev-network
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - backend-dev

  # Redis Cache for Development
  cache-dev:
    image: redis:7-alpine
    container_name: eve-profit-cache-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - eve-dev-network

# Volumes for development
volumes:
  backend_cache:
    driver: local
  frontend_node_modules:
    driver: local

# Development network
networks:
  eve-dev-network:
    driver: bridge
